- hosts: fz_mysql_master
  remote_user: root
  vars:
  - remote_dir: /root/
  tasks:
  - name: copy Mysql-5.6.30 packet
    unarchive: src=/root/fangzhou/packet/MySQL-5.6.30-1.el6.x86_64.rpm-bundle.tar dest=/root/  creates=/root/MySQL-server-5.6.30-1.el6.x86_64.rpm
  - name: copy my.cnf to mysql_server
    template: src=/root/fangzhou/conf/my.cnf dest=/etc/ owner=root group=root mode=0644
  - name: create mysql user
    user: name=mysql system=yes
  - name: create log,data dir
    file: path={{ item }} owner=mysql group=mysql mode=0755 state=directory
    with_items:
      - /var/lib/mysql
      - /data2/mydata
      - /var/log/mysqld
      - /data4/mysql56_log
  - name: copy my.cnf to remote host
    template: src=/root/fangzhou/conf/mysql/my.cnf dest=/etc/ owner=root group=root 
  - name: install Mysql-5.6.30
    yum: name={{ item }} state=present
    with_items:
      - /root/MySQL-server-5.6.30-1.el6.x86_64.rpm
      - /root/MySQL-client-5.6.30-1.el6.x86_64.rpm
      - /root/MySQL-devel-5.6.30-1.el6.x86_64.rpm
      - /root/MySQL-embedded-5.6.30-1.el6.x86_64.rpm
      - /root/MySQL-shared-5.6.30-1.el6.x86_64.rpm
      - /root/MySQL-shared-compat-5.6.30-1.el6.x86_64.rpm
      - /root/MySQL-test-5.6.30-1.el6.x86_64.rpm
      - epel-release
      - MySQL-python
  - name: enable mysql and start mysql
    service: name=mysql state=started enabled=yes
  - name: get mysql default password
    shell: awk '{print $NF}' /root/.mysql_secret 
    register: default_pass
    ignore_errors: true
  - name: update mysql default password
    shell: mysqladmin -uroot -p{{ default_pass.stdout }} password 123456
    ignore_errors: true

