- hosts: fz_mysql_master
  remote_user: root
  vars:
  - webapp_dir: /usr/local/gvis/webapps
  - local_dir: /root/fangzhou
  tasks:
  - name: copy mysql password file
    copy: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
    with_items:
      - { src: "{{ local_dir }}/conf/my.cnf", dest: '/root/.my.cnf', owner: root, group: root, mode: '0600' }
      - { src: '{{ local_dir }}/sql/gvis_20161206.sql', dest: /root/, owner: root, group: root, mode: '0644'}
    tags: sql2
  - name: import xiaojinku db sql file
    mysql_db: name=ruler state=import target=/root/gvis_20161206.sql
  - name: create mysql user
    mysql_user: user=gmanager host='%' password='gm@#1479' priv='gvis.*:ALL'

- hosts: 10.111.32.200
  remote_user: root
  vars:
  - webapp_dir: /usr/local/gvis/webapps
  - local_dir: /root/fangzhou
  tasks:
  - name: cp and unarchive tomcat to remote host
    unarchive: src=/root/fangzhou/packet/apache-tomcat-7.0.70.tar.gz dest=/opt/ owner=www group=www creates=/usr/local/gvis
  - name: modify dir name
    shell: "{{ item }}"
    with_items:
      - test -e /usr/local/gvis || mv /opt/apache-tomcat-7.0.70 /usr/local/gvis
      - chown www.www /usr/local/gvis
  - name: delete default webapps
    file: path={{ item }} state=absent
    with_items:
      - "{{ webapp_dir }}/ROOT"
      - "{{ webapp_dir }}/manager"
      - "{{ webapp_dir }}/host-manager"
      - "{{ webapp_dir }}/examples"
      - "{{ webapp_dir }}/docs"
  - name: create webapps dir ROOT
    file: path={{ item.path }} owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }} state={{ item.state }}
    with_items:
      - { path: '{{ webapp_dir}}/archbase', owner: www, group: www, mode: '0755', state: directory }   
      - { path: '/data4/share/gvis', owner: www, group: www, mode: '0755', state: directory }
  - name: create link file to archbase
    unarchive: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} creates={{ item.creates }}
    with_items:
      - { src: '{{ local_dir }}/war/archbase.war', dest: '{{ webapp_dir }}/archbase/', owner: www, group: www, creates: '{{ webapp_dir }}/archbase/WEB-INF'}
  - name: copy mysql password file
    copy: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }}
    with_items:
      - { src: '{{ local_dir }}/conf/tomcat/gvis.xml', dest: /usr/local/gvis/conf/server.xml, owner: www, group: www}
      - { src: '{{ local_dir}}/conf/gvis/application.properties', dest: "{{ webapp_dir}}/archbase/WEB-INF/classes/", owner: www, group: www}
      - { src: '{{ local_dir}}/conf/gvis/db.properties', dest: "{{ webapp_dir}}/archbase/WEB-INF/classes/", owner: www, group: www}
  - name: start gvis tomcat
    shell: ps aux |grep -v 'grep' |grep 'gvis' || su - www -c '/usr/local/gvis/bin/catalina.sh start'
