# edirtor: haifeng
# 2016/12/8 14:00
- hosts: 10.111.32.163
  remote_user: root
  vars:
  - webapp_dir: /usr/local/xiaojinku/webapps
  - local_dir: /root/fangzhou
  tasks:
  - name: cp and unarchive ssh to remote host
    unarchive: src=/root/fangzhou/openssh-7.3p1-bin.tgz dest=/usr/local/ owner=root group=root creates=/usr/local/sshd
  - name: copy openssh-7.3p1 boot script
    copy: src={{item.src}} dest={{item.dest}} owner={{item.owner}} group={{item.group}} mode={{item.mode}}
    with_items:
    - { src: /root/fangzhou/conf/init/sshd, dest: /etc/rc.d/init.d/sshd, owner: root, group: root, mode: '0755'}
    - { src: /root/fangzhou/conf/sshd/sshd_config, dest: /usr/local/sshd/etc/, owner: root, group: root, mode: '0644'}
    notify:
      - restart sshd service
      - restart httpd service

  handlers:
  - name: restart sshd service
    service: name=sshd state=restarted
  - name: restart httpd service
    service: name=httpd state=restarted
    
