- name:  install zabbix-agent
  user: root
  gather_facts: false
  vars:
  - zbx: "zabbix_agentd.conf"
  - Hostname: PK-XY-Host{}
  - zabbix_old: /usr/local/zabbix-2.4.2
  - zabbix_dir: /usr/local/zabbix
  hosts: zabbix
  tasks:
#  - name: yum libselinux-python
#    yum: state=present name=libselinux-python
  - name: tar zabbix-2.4.2.tar.gz
    unarchive: src=/root/songchunhui/zabbix-2.4.2.tar.gz dest=/usr/local/
    tags: lai
  - name: create user
    user: name=zabbix state=present
  - name: yum gcc
    yum: state=present name=gcc
    ignore_errors: True
  - name: configure
    shell: chdir={{zabbix_old}} ./configure --prefix={{zabbix_dir}} --enable-agent
  - name: make
    shell: chdir={{zabbix_old}} make
  - name: make install
    shell: chdir={{zabbix_old}} make install
  - name: file chmod
    file: path={{zabbix_dir}}/ owner=zabbix group=zabbix recurse=yes
  - name: copy zabbix_agentd
    shell: cp -fr /usr/local/zabbix-2.4.2/misc/init.d/fedora/core/zabbix_agentd /etc/init.d/
  - name: chmod 755 zabbix_agentd
    file: path=/etc/init.d/zabbix_agentd mode=755
  - name: sed zabbix_agentd
    lineinfile: dest=/etc/init.d/zabbix_agentd regexp=BASEDIR=/usr/local  line=BASEDIR=/usr/local/zabbix
    tags: two
  - name: crontab
    cron: name="custom job" minute=*/10 hour=* day=* month=* weekday=* job="ntpdate cn.pool.ntp.org"
    ignore_errors: True
  - name: echo /etc/services
    lineinfile: dest=/etc/services line={{item}}
    with_items:
      - "zabbix-agent      10050/tcp"
      - "zabbix-agent      10050/udp"
      - "zabbix-trapper    10051/tcp"
      - "zabbix-trapper    10051/udp"
    tags: song
  - name: ifconfig hostname
    shell: ifconfig eth0 | awk '/inet addr/{print $2}' | awk -F "." '{print $3"."$4}'|xargs -I {} sed -i "s@Hostname=Zabbix server@Hostname={{Hostname}}@" /usr/local/zabbix/etc/zabbix_agentd.conf 
  - name: sed server
    lineinfile: dest=/usr/local/zabbix/etc/zabbix_agentd.conf regexp=Server=127.0.0.1  line=Server=172.16.4.8
  - name: sed ServerActive
    lineinfile: dest=/usr/local/zabbix/etc/zabbix_agentd.conf regexp=ServerActive=127.0.0.1  line=ServerActive=172.16.4.8:10051
  - name: sed Timeout
    lineinfile: dest=/usr/local/zabbix/etc/zabbix_agentd.conf regexp=Timeout=3  line=Timeout=30
  - name: sed UnsafeUserParameters
    lineinfile: dest=/usr/local/zabbix/etc/zabbix_agentd.conf regexp=UnsafeUserParameters=0  line=UnsafeUserParameters=1
  - name: Include=/usr/local/zabbix/etc/userparams/zabbix_agentd.userparams.conf
    lineinfile: dest=/usr/local/zabbix/etc/zabbix_agentd.conf line=Include=/usr/local/zabbix/etc/userparams/zabbix_agentd.userparams.conf
  - name: mkdir userparams
    file: path=/usr/local/zabbix/etc/userparams state=directory
  - name: touch zabbix_agentd.userparams.conf
    file: path=/usr/local/zabbix/etc/userparams/zabbix_agentd.userparams.conf state=touchZ
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    {PK-XY-Host9.73:proc.num[,,,bin/justswitch].last()}=0&{PK-XY-Host9.74:proc.num[,,,bin/justswitch].last()}=0
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
  - name: mkdir script
    file: path=/usr/local/zabbix/script state=directory
  - name: setenforce 0
    shell: setenforce 0
    ignore_errors: True
  - name: del {{zabbix_old}}
    file: path={{zabbix_old}} state=absent
    ignore_errors: True
  - name: script
    script: /root/songchunhui/speed.sh
  - name: sed selinux
    lineinfile: dest=/etc/selinux/config regexp=SELINUX=enforcing  line=SELINUX=disabled
    ignore_errors: True
  - name: iptables stop
    service: name=iptables state=stopped
    ignore_errors: True
  - name: chkconfig iptables off
    shell: chkconfig iptables off
    ignore_errors: True
  - name: chkconfig --level 345 zabbix_agentd on
    shell: chkconfig --level 345 zabbix_agentd on
  - name: zabbix_agents tarted
    service: name=zabbix_agentd state=started
    tags: one
